<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="APATIDAR" failures="1" tests="1" name="Default test" time="456.97" errors="0" timestamp="2024-11-15T19:01:57 IST">
  <testcase classname="Selenium.Practice.demo2" name="test2" time="451.382">
    <failure type="junit.framework.AssertionFailedError" message="login failed for users: [awarehime@morstan.com, agoldfarb@morstan.com, jabney@neccsouth.com, arosenberg@morstan.com, amakabali@morstan.com, ARamsey@Morstan.com, jbond@morstan.com, msilver@morstan.com, pablo.zapata@hullco.com, pfitzgerald@morstan.com, rose.bates@hullco.com]">
      <![CDATA[junit.framework.AssertionFailedError: login failed for users: [awarehime@morstan.com, agoldfarb@morstan.com, jabney@neccsouth.com, arosenberg@morstan.com, amakabali@morstan.com, ARamsey@Morstan.com, jbond@morstan.com, msilver@morstan.com, pablo.zapata@hullco.com, pfitzgerald@morstan.com, rose.bates@hullco.com]
at junit.framework.Assert.fail(Assert.java:47)
at Selenium.Practice.demo2.test2(demo2.java:115)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="Selenium.Practice.demo2" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test -->
